### ISSUE TITLE
[Documentation] Update Readme

### ISSUE THREAD

**Issue by RavindraP04** [Priyadarshan2000/Hacktoberfest_2k23#2]
Change year from Hacktoberfest 2022 to 2023 in the Readme

![image](https://github.com/Priyadarshan2000/Hacktoberfest_2k23/assets/98400348/03bb1525-882d-4322-a16d-da161a3d3feb)

**Comment by RavindraP04** [comment]
Can I work on this ?

**Comment by Yasir761** [comment]
Hey assign me this under Hacktoberfest tag.

**Comment by Priyadarshan2000** [comment]
@RavindraP04 There is no need for a documentation update in This Repo. You can contribute only to JS projects.
keep hacking 👍

**Comment by SUVAMPATTANAIK** [comment]
Can we add any other project to this repo or work on current one only ??

**Comment by Priyadarshan2000** [comment]
> Can we add any other project to this repo or work on current one only ??

@SUVAMPATTANAIK  yes you can add any js project on this repo.
